"""add reminder_date, reminder_time, and email to Task

Revision ID: b7948240ce4e
Revises: 
Create Date: 2024-12-04 00:57:50.840969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7948240ce4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('reminder_date',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('reminder_time',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('reminder_time',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('reminder_date',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
